name: class-list
version: 0.1.0.0
github: "githubuser/class-list"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/class-list#readme>

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers >= 0.2 && < 1
  - hashable >= 1.3 && < 2
  - aeson >= 1.5 && < 2
  - bytestring >= 0.10 && < 1

library:
  source-dirs: src

executables:
  class-list-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - class-list

tests:
  class-list-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - class-list
